### PR TITLE
Effect rewrite

### PR DESCRIPTION
**Pull request by LoLei**
Code by @GM-Script-Writer-62850

### CODE REVIEW

**Comment by GM-Script-Writer-62850** [comment]
[razer-cli.patch.zip](https://github.com/LoLei/razer-cli/files/5898208/razer-cli.patch.zip)
* fix typo
* change variable name join_str -> glue_str
* clean up
* add support for [backlight zone](https://github.com/openrazer/openrazer/blob/master/pylib/openrazer/client/fx.py#L1024)
* add manual entry for `-l`
* fix bug where if you provide 2 effects for 3 zones it errors

**Comment by GM-Script-Writer-62850** [comment]
looks like part of `parse_color_argument` is broken, namely the for loop, here if the fixed version
```
def parse_color_argument(color):

    if len(color) == 1:
        # Hex: Just one input argument
        rgb = color[0]
        if rgb.lower() == "random":
            rgb = util.get_random_color_rgb()
        else:
            rgb = util.hex_to_decimal(rgb)
    else:
        if len(color) == 3:
            # RGB: Three base10 input arguments
            rgb = []
            for i in color:
                if i.lower() == "rng":
                    rgb.append(util.randint(0, 255))
                else:
                    rgb.append(int(i))
        else:
            print("Unknown color input:", color)
            rgb = util.get_random_color_rgb()

    return rgb
```

**Comment by GM-Script-Writer-62850** [comment]
[patch.zip](https://github.com/LoLei/razer-cli/files/5899882/patch.zip)
* Add support for pulsate and blinking effects
* Simplify some of the dpi code

**Comment by GM-Script-Writer-62850** [comment]
Is this an effect:
https://github.com/openrazer/openrazer/blob/master/pylib/openrazer/client/fx.py#L676-L691
If so I could add it as with the effect usage of active,1 (set true) and active,0 (set false)

**Comment by LoLei** [comment]
What exactly does "active" do? Just enable/disable the device? If so I wouldn't say it's an effect.

**Comment by GM-Script-Writer-62850** [comment]
no idea what active does, i just saw it in openrazer's code, making it accessible as a effect is easy as about +5 lines, now is it different from the none effect?

**Comment by LoLei** [comment]
If it's that easy, you might as well add it.

**Comment by GM-Script-Writer-62850** [comment]
My current install has a lot of changes for `-l` upgrades, so sorry for the lack of a patch file, while doing this i changed the way i was testing for some features and in doing so i changed the indention level in the effects function, i also made manual entries a file cause it was getting ridiculous
so i am trying to keep this pull request on topic
Just add this to the effects section (i did this below brightness)
```
                    elif effect == 'active':
                        used = 0
                        if len(arg) == 0:
                            b = True
                        else:
                            b = bool(arg[0])
                        prop.active = b
                        if args.verbose:
                            debug_msg[zone].append(["Setting", effect, 'to', b])
```
add active to settings.EFFECTS
Changes to effect manual
```
Effect arguments can any of the following:
    breath_dual, breath_random, breath_single, breath_triple, none, reactive, ripple, ripple_random, spectrum, starlight_dual, starlight_random, starlight_single, static, wave, and multicolor 
Each effect is applied to 1 zone, remember that 'logo,right' is 1 zone and 'left right' is 2 zones
The following effects support a second argument by adding a comma followed by a number:
    active, brightness, reactive, starlight_single, starlight_dual, starlight_random, wave, and multicolor
    active,[0-1]
        0 sets active to False
        1 sets active to True
        Defaults to True
    brightness,[0-100]
        % brightness (this is the PWM Duty Cycle)
        If not specified it will be 100
        This is the same things as --brightness
        Example usage:
            razer-cli -e static brightness,75 -z logo logo -c FF0000
    reactive,[1-4]
        1 = 500ms, 2 = 1000ms, 3 = 1500ms, and 4 = 2000ms
        If not specified it will be chosen at random
    starlight_single,[1-3], starlight_dual,[1-3], and starlight_random,[1-3]
        1 = fast, 2 = normal, and 3 = slow
        If not specified it will be chosen at random
    wave,[1-2]
        1 = right and 2 = left
        If not specified it will be chosen at random
    multicolor,[0-∞]
        0 = assign random colors for everything (does not consume colors)
        1-∞ = the number of colors to use from -c
        This defaults to 0
    The following effects do NOT consume colors:
        none, active, brightness, breath_random, spectrum, starlight_random, and wave If you only specify 1 effect it will be applied all zone

```

**Comment by LoLei** [comment]
I added the changes, but using the "active" "effect" This doesn't seem to work:
```python
Traceback (most recent call last):
  File "/home/me/.local/bin/razer-cli", line 33, in <module>
    sys.exit(load_entry_point('razer-cli', 'console_scripts', 'razer-cli')())
  File "/home/me/git/razer-cli/razer_cli/razer_cli.py", line 762, in main
    set_effect_to_all_devices(device_manager, effects, color, zones)
  File "/home/me/git/razer-cli/razer_cli/razer_cli.py", line 566, in set_effect_to_all_devices
    set_effect_to_device(device, input_effects, color, zones)
  File "/home/me/git/razer-cli/razer_cli/razer_cli.py", line 376, in set_effect_to_device
    if hasattr(prop, effect) or effect in ["multicolor"]:
  File "/usr/lib/python3.9/site-packages/openrazer/client/fx.py", line 680, in active
    return func()
  File "/usr/lib/python3.9/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/dbus/service.py", line 658, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3.9/site-packages/dbus/service.py", line 248, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: getLogoActive is not a valid method of interface razer.device.lighting.logo
```

I'd just leave it out completely then.

**Comment by GM-Script-Writer-62850** [comment]
probably did not notice due to the rework i did to the way i validate if a property exist since then. guess we can tack it into the upcoming patch for `-l`

**Pull request merged**
