### PR TITLE
Added alternative installation method to the README

### PR DESCRIPTION
**Pull request by ifohancroft**
Python's pip has not been working recently, so I added an alternative installation method to the README.

### CODE REVIEW

**Comment by LoLei** [comment]
Interesting!

Instead of `sudo python setup.py install`, does `pip install . --user` also work?

What kind of error are you getting with the normal pip installation via PyPI? ([`pip install razer-cli`](https://pypi.org/project/razer-cli/))

**Comment by ifohancroft** [comment]
The last time I tried pip was looking for razer-cli so I was doing pip search and it failed with the error about PyPi's something API being deprecated, so I completely uninstalled pip (I don't really like using it anyway as it's harder to keep track of what I have installed from there), however, if you'd like me to, I can install it and try? Perhaps it would work but I thought it's worth it having the alternative installation method

**Comment by LoLei** [comment]
It's fine you don't need to install it again.

Could you add the `pip install . --user` method to the Readme as well though please? As a further alternative to `sudo python setup.py install`, while we're at it.

**Comment by ifohancroft** [comment]
Sure! I'll comment here when it's done since I am not sure if you get notified for a second commit to an existing PR.

**Comment by ifohancroft** [comment]
Done.

**Comment by LoLei** [comment]
@all-contributors please add @ifohancroft for doc

**Pull request merged**
