### PR TITLE
Add code submitted by @GM-Script-Writer-62850

### PR DESCRIPTION
**Pull request by LoLei**
@GM-Script-Writer-62850 let me know if I missed anything

### CODE REVIEW

**Comment by GM-Script-Writer-62850** [comment]
Good to know `if device.has("poll_rate"):` does work, was not sure if i should have used `if device.poll_rate:` or not instead since i only have a mouse,

**Comment by LoLei** [comment]
Yeah it works for me with e.g.:
`razer-cli -d "Razer Lancehead Tournament Edition" --poll 500`

It even shows an error if you try a rate that isn't supported.
```
`razer-cli -d "Razer Lancehead Tournament Edition" --poll 100`
ValueError: Poll rate "100" is not one of (125, 500, 1000)
```

**Comment by GM-Script-Writer-62850** [comment]
on a mouse that supports it it would work, not sure it it would give the proper error if the devices does not support the feature, like maybe a keyboard

error message comes from openrazer, those values appear to be hard-coded there

**Comment by LoLei** [comment]
For my keyboard it says:
`Device does not support setting the polling rate`

So all is working fine I suppose.

**Comment by LoLei** [comment]
@all-contributors please add @GM-Script-Writer-62850 for code

**Comment by GM-Script-Writer-62850** [comment]
then i guess it should good

i know doing this does not hurt anything, but you know you can do this with how the code is written
```
.local/bin/razer-cli -ll -llh
```
maybe that should not be allowed? not like it matters, you clearly know what you are doing if you do that

**Comment by LoLei** [comment]
You're right, it's a minor thing. I added an issue (https://github.com/LoLei/razer-cli/issues/39) for later if me or someone else likes to fix it.

**Comment by GM-Script-Writer-62850** [comment]
Maybe i could/should have done `if device.capabilities['poll_rate']:` instead of `if device.has("poll_rate"):`

**Comment by GM-Script-Writer-62850** [comment]
also found a neat feature:
`.local/bin/razer-cli --dpi 1200 --dpi print`
too bad it does not work as expected

cause you can do this:

- `.local/bin/razer-cli --dpi print --poll print`
- `.local/bin/razer-cli --dpi 800 --poll 125`

Also why does it say `Starting Razer colors script...` when i use -v i thought i fixed that when i moved the color stuff to under the arg check for color input stuff

Why are we printing that if you are just using `-v`, if we are going to print someone for using `-v` it should be running in verbose mode or something, if you are gonna print "Starting Razer colors script..." it should be when staring some rgb related stuff not when we just parsed the arguments

**Pull request merged**
